---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digital-ocean-token
  namespace: external-dns
spec:
  encryptedData:
    DO_TOKEN: AgBAi9agCC17dt1KID1jd9FKC3C3s/TJDk0K5Zd+7Uy9rHfAoP8OOwoi+4u0ci++gSxawUhCfVgKrPcTzePc4c+id1NJnrd2pFUpLgBOVknkeFZ6wG1zXphSuP1mIKa96kAIqkIyfFGU1fsK7dL/OSnUfvZRD4HuyJf1DnOHiq7rHANGFLltUlPPve3O/4GonUJBXdyXW7s1jpck+FpdlXiENRvxSnMylxzSghD18fQjOjYIBN4a3fa0OyoVDGFmTjclm0MzbWZ4w9NJZppEibcwsl3ym4HdGM4JNwANYujbOwd0Ib+R5G3tOtncP14dsv/3EOKqLtSdaUA0Dh34aYfYbAaT4/erRuw5/L8guACWsBiBZ0dbU9D9mmJUGF5phWhz8IxxmnrsbdP1sPNOS4fJdjxjo5f9yETX6Cy/Q0SULm7P2aFmgK888CEKmnunz/Bqsv4ddicGyKcDXoC/WWYHCVhML1CkL1aDV1/MqH55mZZEWS5t+jrpNJ1pvSLd8kszCk7spvE311M83geQ57TRwYURH1aSgMGHHGqDVAmHVOEB2ghe90IZND4GQpuO1ZQY0eYpv9WXhWaDYJ2jd/UQPk9JKJvt2jh5mz1KI+MgeigTmjbfcPsVVhsSXrMz1o8K+fSI6En36y0k+BjLibFg70xPYOZtpEUpLdy+YlXcPRdlSOYMjfV7qHl4TfprrSB2TaxLnm0kGilFnXuT1ZgQSii8RxNKbnHBNv6xAFgWpcK/EQRgcIpb4c5IWK+70dgChHQSg0Owkh3O+EzBuGpp2n3v98RKfg==
  template:
    metadata:
      creationTimestamp: null
      name: digital-ocean-token
      namespace: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values:
    provider: 
      name: digitalocean
    sources:
      - gateway-httproute
    env:
      - name: DO_TOKEN
        valueFrom:
          secretKeyRef:
            name: digital-ocean-token
            key: DO_TOKEN
    logLevel: debug
