---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "33.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
        statusAddress:
          ip: 97.126.64.237
    ingressClass:
      enabled: false
    gateway:
      enabled: false # this disables traefik auto-creating a gateway
    priorityClassName: "system-cluster-critical"
