---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digital-ocean-token
  namespace: cert-manager
spec:
  encryptedData:
    DO_TOKEN: AgAwner8IIrpB+/Sg1cVl91VlDLzDX7Dg75J09sQbbMYlcO9R9yKwfIlDaaRtBiJF6UkCfMDKQOV3dVPc8rlFHVLKtw1v5AYHbOWykPfCAv5+Ft7jC4t4knHoX63x5mr6+dYSfDWloJk+izGRXrl8M7L92Ui9TW5K5jAwPDfSmllFQxbLFoqGdpfj4o2o2fXZ9/q1/cVZ0uZV+534GZa8NoD4opaTaRCJnGRBpeG6zJ3oIxz0+AjHo6JVfa1Oq1k48iVf//jaNxNRri7mcbyc4dR3vV8WZY4a+S8IGexnKfzjhd+3anGSjBRok93smF134waH2c6UHUTv10HINJB3/DcK1XhIUfLUhMdpw5DfWyz/Oyxm7nvL7a/obkLbXQ4Sw/y4F5DEwR+DPdHDg+8VauoAIk3/E/F1GVqDP2thKUnPP3kl5/AHHT9eXXPQsKcnqsl73DSzIgbSa/FkPr2/RTp1/Bez9kOh7pI3hosuG1BsQX9EluxijedplEP4gSnUMPifzZVFJ40A4FZl9uTHKHNjPKMLEu4bDoiwK60T0HE7T1wRsGSQL20vjV7xM79QFSg//t2ppN9qOGs637zCvbNsF3nQUs1DLmVfrMvWGXQA2sgkDLE8r+3Gc0Fy9YH8UGHFnDrUSgtfwiu0vsgEeT2iVMtjDDRhjk0W3YRX6CsXcloJS1oYY9SuzlLr9uzcZx3IaVDRzeXp9AczkoiAFQRTKxXr4cUF4N4WWElSuOqQzCOV1HHuRT2GtPBbD/+dFz4CcdKyjc4YeFm6P1JOVONei0Z9+4YvQ==
  template:
    metadata:
      creationTimestamp: null
      name: digital-ocean-token
      namespace: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: nicolasbrassard10401@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-traefik
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digital-ocean-token
              key: DO_TOKEN
