---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: ">=0.1.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: capacitor
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: capacitor
  namespace: flux-system
spec:
  policyTypes:
    - Ingress
  ingress:
    - {}
  podSelector: {}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nico-basic-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgBYXf5kB/nNTEG3GMYBznT7vNSqjEaoObcKyucbUgBUG6qRN5HofBkwnH6BWchsV+d7G7nbQRcYuGGh+7Ia1K1V4QOykN8G1c/vej7HqS3M03ApmZfLOav7KNmNBD+Y0bssxU3pTxCH17em6pk4y4wEjkbees0dQQvzTdd9P3kXxb3YDV2SFlSJhQfUJ0kmdXfifOkETkFKJGVO5A8UwLwRzYOW/zuQ+Ukgw2iF7MCKU8VgLJhGUC5GBUuZXyRKFxlg+/XucidwoNd1jKbdDnypJwh6jqvCUD3AmxCQfeJz8dcrd2bEXrHllWEaVolCt38J9va1RDXuCWthdu7cIYehzQx1D9ZxiK+1Zh0qI7XjCROYuMupU2rAl6dZ++V0boIJDEZeSS/mBUD6Ia/8NRc2aHcbNjrx3kKAqrqa+d0oYfFmcl0ASdKCgJWXcMbnDadq0zBJmxBTcoELAZqmLPNv5xhFasSlHHAZlkFwwtQ02I9ragK5Cz/wpuK6z6EZ23EetRa2h6nGhF+Sf8FhgiYCYJmJCincOR0j8aXYLJKpbirQ1KPgPImv02JSW0TNL8Euo5Gqi2YxaaiMrtTVDlCUNah7G2NpXqbp52CsFzvydZMXoHJzmzcywTg02elXYmLSGoyNd+iQRobxLzgRU0vgKeSB2f4wQ9CxTHhkzQA2DhXF8TK6EcOP8t5BBkfcKN/6/kBbqi53/L4=
    username: AgAZ5CpuGaC5g102/obV1XGj6vHFxWglGJfUSy4OGaTGxMjeJEYaCjOyHUG7PJXr8P6OQwyGxzR3Q4WkEfVb2GWzPWBO8CTOCIG4fHQdo9zRIJev6bWEkqIxhcciOukcLNz5W3ujPZAvpPlF9HV1S+fXX1jdFV+qfl3+VBJWUmwXVuqh03AH4EYm0JpCb60NvYEje0gNJUT4g7l0McenPCV36rb0rZPJ/k7Tl0//2hq3DZ8jVABSdSpuHcpgLORJ8VjCjm+IWFexilTZolGpslyIVCaPV1IoSkrVcMlAfU2MBBmIFgZEOCsGMwSla3A6Qz7bZkpNNlbv6uhuUaFo4XxZLOxNLGiV/5yowSMvN9/k0G9mniGq4bV3PfJRlmnq5dZqqcuGztGrKxlYyEelCrH/FZoSJ7JHh0p1hoJHm2Ic18Ak0unVPIJ3LvYa5uOTSsz+hTlZ3Wn1/9s7RlNADLNR2+wrb9Z8IZc5r6iRCiqV0DRTotlK30UxbJfsPns97/QuXlHv4SMdRsIjlAM1vL7n/GtD7NMiGLWJaoWpQpwe7DsQSsPYGWyTfuVMx7cGiOgW+LR5ARB8K/jw+K4r3NnYF7SPuw3g4YXXLRqCm4WDilQ+6+ierDL30++INS8Tkn42a5oxDKysb+AeqApsx/QFfpt6SWEzBqHP5KY7h+IGYcK6xZn9Tl52kAa8tnA0Sqf7Yohq
  template:
    metadata:
      creationTimestamp: null
      name: nico-basic-auth
      namespace: flux-system
    type: kubernetes.io/basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: flux-system
spec:
  basicAuth:
    secret: nico-basic-auth
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: capacitor
  namespace: flux-system
spec:
  hostnames:
    - flux.nikuber.com
  parentRefs:
    - namespace: traefik
      name: traefik
      sectionName: https-subdomain
  rules:
    - filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: basic-auth
      backendRefs:
        - name: capacitor
          port: 9000
