---
apiVersion: v1
kind: ConfigMap
metadata:
  name: static-website
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Simple Website</title>
    </head>
    <body>
        <h1>Welcome to My Static Website!</h1>
        <p>This is a simple static site served using static-web-server.</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: static-web-server
          image: joseluisq/static-web-server:latest
          env:
            - name: SERVER_HOST
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_ROOT
              value: /static
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: static-files
              mountPath: /static
              readOnly: true
      volumes:
        - name: static-files
          configMap:
            name: static-website
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  selector:
    app: source-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homepage
  namespace: default
spec:
  hostnames:
    - nikuber.com
  parentRefs:
    - namespace: traefik
      name: traefik
      sectionName: https-topleveldomain
  rules:
    - backendRefs:
        - name: homepage
          port: 8080
