---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: 1.8.9
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          ports:
            - containerPort: 25565
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: default
spec:
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: minecraft
  namespace: default
spec:
  parentRefs:
    - namespace: traefik
      name: traefik
      sectionName: minecraft-protocol
  rules:
    - backendRefs:
        - name: minecraft
          port: 25565
