---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: muse-credentials
  namespace: default
spec:
  encryptedData:
    DISCORD_TOKEN: AgAtZipcZi6vnprNEQ7vOxLyXiUdZlsbv5aZjJWHZDkgmo3SL1zY4sety9W5GhC/HuLq7hJMNtBNYZ/qcJIYY6BpvPVGghl0BRId025oQ8I7fRITyRFb4UesxMkuWAldjQgutHdd6pRRiduhr8Ex214aBv0ZXxWIyw1Ocw+e6JzgJcWhusXR33VwweyJ9mC7/U4/yGc4uucXLFMQPRBeGJAcsz3qQnvdk3YEevyU7bgxWsBsbkLLtOTdFvJrPtfk8iBejTPayFdF5nTlfdHadzc/QJ3BEjtYkSIJZFqD8xIahVIo7cTlnVXfm1ovFLsmQQaHkKvDkKQYzxq9frLDo38gNI5+m5s7uJN4JL6XGJI+AiaBogedVA35bRz7OB8pd2VT1yIisyiewJsMz6qIqPZQbJw5of3QIe6HPTdoIQkDDCy3AhEwOKHbUD9sWhsjTC2GheXQIhd/4YWgKs3KbPvMOzDuEy+rrfZf3/tqxgLNnompJ+/rN6srhQYhLYu9t25aidU9Dw/rOHx0nK8DJmuXmv780P92HjfZUwINcAe/nrBPuRmxtyeNhvU4Upt+JehDKgNqe8aQvzKlOyCWKgICPg0wmaM70vwvRt0cWK2UgPg4VqsIAP7vUF7lL8/YEipPm7bEf+8kbAxK9mSx5Swazce0KhtTUNIXAvrHwCcYGxypyrd/BkGAb7wzHLsZ0KisnAc/OKOpWR3IE2+DBwyXUBjTUBmUzwKMqbZp5Ogi+Q/utWvPlbKgweFfaPCPHFAnXOezdPCN8TGYAxCiuwQSG3v8d8jj
    SPOTIFY_CLIENT_ID: AgA/PK8l7d8lGyafm2oSBfHB5dvOFWqs/1rx2KGYvcAeqj9g9U5INoeASvnlIcBm1ZsHlFzwgeLDiYNk98hejyuD9HM/ufMvy7Bp8REJh0Ld+6kszLZ2NDUWFrCk80jjidv3IQKcKW71IfpV0KPgIBwAjjM6r4a8DzNPpj70S9cyS7N5yGlv6YUYa9zGKwVQiTK+5EUDo15Vp99v7M3uCYMxjpAZqvaYNP8qJLuunz2DQqstj8+4L9faE/xm/4c6XzUe5LqjRztj5sRGxOwsPxQ0TfSGW+vl6wYIpSeKcvNoHqYNQy7q4+XKoIiLyixpTRVA5gBvRpZxAdob98exgrTWnM7Ky9Q0CBSDGywN981Z+xF97twAmbhDJpEJjw2P1t7kqWSDlj8KWlTwppu+8gR8yVZue0AZ+/eDPdOHAYKZq4luJFhBAXcOfoZqblo2zn7Ryah6f6fFleVhQQfbh/Oc8HN4WsolaVWnNWb8i1H17WvRlDcYqxQK6Z/PPV6piGDCCy0iM71BvBCTkCctbbHPnmjOQ9R415EVQ95JlJnogGslfxmSdZx2QiopySc3LisqKjHvgXLDj4y/IkZ2SWNZ1STMWtXatRukfy26EmrriBLzQLu7KEwBZzOPDIWyb/B3y7KrQCQ1vRvrHZnLKSY6JTBccNXYBBFDglB0HAYI//k4IJfXaJXH6hTEtLvj/cIMAJfBv7KNM2zwNbX1ooKr2ARak4lObJ2SSW9gbcbZ7Q==
    SPOTIFY_CLIENT_SECRET: AgCMKzvh2LAzJcogD5b5X0WHW1qIjk4rfHQZqIw5BoKZ8hfhSGaqkXCVzgGtEXcMQvMpAhO7beNhyFCpayd3YSYV289FxwNrDwoFbJtkylxQlka3jiuPsW4s3Ramqz3iO2TFbIlxxVW+LIGYDaj0dLun3VO2YoQRwlvls6PlqmzM5IjRxHEpUbMO0Pt48VKCcxnsLHGB1UIoltW8nvREp0pBo7RWwZ0i6zSdxM2jp4ktx0gcUro77QEhjgpUTRWMm0RKPfOW5gYB6jocqdnvfY4tJ5m14qUazmv8fHyJwlTRMPR1DQV+28MTq8z52z/dBiJQTMxszoH74qmUpsdfwJyVrAdH1xbRhUS1gxjyjXncKv2OIMvHE/jrflKTaMzIGuf0Uj4K3LiGzSEUHZ4ldycRnyhIH/ZAtTz13xMTCbJ9/1egRjx1ZV53PLUZScodFwWoQM0NEHtARw0JmgbpuXy711sA7zQYgs8jJLizbGHGvblJuNVNyBagdfVxxTNaJ76KOsVn3BICvFgOcqsYurvmhViF+cJ6hvbtXh93SsDNwE/XosV6hqr/bGwL04buMn9Uv86s7PpEGl+ERjj5qDdp4nO/UZh07jM3wZThYNIfBgbgLEhCx+L/Vq3EDRtfWZPwQa+fTtnu8/JJfRpDoZGXQQERjTIO8ig19cXGpl00TnHf+17cREKcUS+uYDaaHauDn0X92JL+lX0FU0iZXc5MAMPL9PIsU3DxamhJeob7pA==
    YOUTUBE_API_KEY: AgCfjqpzynfZNlrapL/PB0mQr277nZy03T9vlYOOlCmPD4zwlcJgP2loJmJ8IZu23EC4SoOmAEw0/HgccX5Q4tvxOBw27vXgfP2I0Nv5SM9ipbyhtqDvUMo9AmdMQxjmSDn9EFLmQuNX35rTmxoXCo7ejbY/EOC/W9wiGq6bGVnD6rmENVf0JJSJYjHWA24Bg6Au2S6wZILwJoXu+GWpvw6qLby824ZxXXz94tlSCdF9HgkAOMnefgGZ52xQ5y2tNvJE/oGusaOhQr1rzMO7oI3dx3Qfw9g60oIRl27t/uO2VYjljWR0sqQLgoELKrGsQFSHoOR4mCpNdvJI7XC8WOZu+U7gQlqoR2C4jRbUrgqihiNqlx50iLaOd5dwmL0CmPjxhXPsIU3+73R694Kw8+G04VxiYzfwvGEI5fewm4uvpd1tX9FywEyE6LPFX/4Z/7h+yIkl3cwcJwxJcuKRmy7DfV1PMZiVNtdRywznejyX7W6/O1tvFYwJFznjnNp5fMiOXKHsnh4sGczYBKhV7weaYrKMhcUDtGzQCk/aXCzBMlzLoaehW5VDXx5Gs5bYD8TWfWx58K9sklFwB6Szj7OAD+RPIwWuWa1KU2Q9S5xnt/Hk4LJKi7dCHyk55XwXqTTSPIegTRe1k2sOwx5wAR6u6oPsy7D9qThw8u3+DgoZ1trRrZLRakJd8rZGjhFnGanKZiyXgKC2D4kvbkMwHrKBTeSqpLhxyhWMO1bde+RcJy0X9eFlC/I=
  template:
    metadata:
      creationTimestamp: null
      name: muse-credentials
      namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muse
  labels:
    app: muse
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muse
  template:
    metadata:
      labels:
        app: muse
    spec:
      containers:
        - name: muse
          image: ghcr.io/museofficial/muse:latest
          envFrom:
            - secretRef:
                name: muse-credentials
